/**
 * Stable public kernel API for external consumers.
 *
 * This surface is intentionally narrower than `src/runtime`: callers should
 * use it when they need to start a server, create/connect direct sessions,
 * or consume stable kernel-facing types without depending on internal layout.
 *
 * Semver contract:
 * - `src/kernel/index.ts` is the only source-level public kernel surface.
 * - the package-level `./kernel` entry re-exports this file and shares the
 *   same stability guarantee.
 * - leaf modules under `src/kernel/*` remain host-internal implementation
 *   surfaces and are not covered by the public semver promise.
 */
export {
  createDefaultKernelHeadlessEnvironment,
  createKernelHeadlessSession,
  createKernelHeadlessStore,
  runKernelHeadless,
} from './headless.js'
export { connectDefaultKernelHeadlessMcp } from './headlessMcp.js'
export { prepareKernelHeadlessStartup } from './headlessStartup.js'
export type { KernelHeadlessMcpConnectOptions } from './headlessMcp.js'
export type {
  PrepareKernelHeadlessStartupDeps,
  PrepareKernelHeadlessStartupOptions,
} from './headlessStartup.js'
export type {
  DefaultKernelHeadlessEnvironmentOptions,
  KernelHeadlessEnvironment,
  KernelHeadlessInput,
  KernelHeadlessRunOptions,
  KernelHeadlessSession,
  KernelHeadlessStore,
} from './headless.js'
export type {
  KernelRuntimeEnvelopeBase,
  KernelRuntimeEnvelopeKind,
  KernelRuntimeErrorCode,
  KernelRuntimeErrorPayload,
  KernelRuntimeEventSink,
} from '../runtime/contracts/events.js'
export {
  createDirectConnectSession as createKernelSession,
  connectDirectHostSession,
  applyDirectConnectSessionState,
  assembleServerHost,
  getDirectConnectErrorMessage,
  createDirectConnectSession,
  DirectConnectError,
  runConnectHeadless as runKernelHeadlessClient,
  runConnectHeadless,
  startServer as startKernelServer,
  startServer,
} from './serverHost.js'
export {
  connectResponseSchema,
  type DirectConnectConfig,
  type ServerConfig,
  type SessionIndex,
  type SessionIndexEntry,
  type SessionInfo,
  type SessionState,
} from '../server/types.js'
export { runBridgeHeadless } from './bridge.js'
export { runDaemonWorker } from './daemon.js'
export { createKernelCompanionRuntime } from './companion.js'
export { createKernelContextManager } from './context.js'
export { createKernelKairosRuntime } from './kairos.js'
export { createKernelMemoryManager } from './memory.js'
export { createKernelSessionManager } from './sessions.js'
export {
  KERNEL_CAPABILITY_FAMILIES,
  KERNEL_RUNTIME_EVENT_TAXONOMY,
  KERNEL_RUNTIME_EVENT_TYPES,
  createKernelRuntime,
  filterKernelCapabilities,
  getKernelCapabilityFamily,
  getKernelRuntimeEventCategory,
  getKernelRuntimeEventTaxonomyEntry,
  getKernelRuntimeEventType,
  groupKernelCapabilities,
  isKernelCapabilityReady,
  isKernelCapabilityUnavailable,
  isKernelRuntimeEventEnvelope,
  isKernelRuntimeEventOfType,
  isKernelTurnTerminalEvent,
  isKnownKernelRuntimeEventType,
  toKernelCapabilityView,
  toKernelCapabilityViews,
  KernelRuntimeRequestError,
} from './runtime.js'
export type {
  KernelCompanionAction,
  KernelCompanionEvent,
  KernelCompanionReactionRequest,
  KernelCompanionRuntime,
  KernelCompanionRuntimeOptions,
  KernelCompanionState,
} from './companion.js'
export type {
  KernelContextManager,
  KernelContextManagerOptions,
  KernelContextSnapshot,
} from './context.js'
export type {
  KernelKairosEvent,
  KernelKairosExternalEvent,
  KernelKairosRuntime,
  KernelKairosRuntimeOptions,
  KernelKairosStatus,
  KernelKairosTickRequest,
} from './kairos.js'
export type {
  KernelMemoryDescriptor,
  KernelMemoryDocument,
  KernelMemoryManager,
  KernelMemoryManagerOptions,
  KernelMemorySource,
  KernelMemoryUpdateRequest,
} from './memory.js'
export type {
  KernelSessionDescriptor,
  KernelSessionListFilter,
  KernelSessionManager,
  KernelSessionManagerOptions,
  KernelSessionResume,
  KernelTranscript,
} from './sessions.js'
export type {
  KernelEventType,
  KernelKnownEvent,
  KernelAbortTurnOptions,
  KernelAgentDefinitionError,
  KernelAgentDescriptor,
  KernelAgentFilter,
  KernelAgentMcpServerRef,
  KernelAgentCancelOptions,
  KernelAgentCancelResult,
  KernelAgentOutput,
  KernelAgentOutputOptions,
  KernelAgentRunDescriptor,
  KernelAgentRunFilter,
  KernelAgentRunStatus,
  KernelAgentSnapshot,
  KernelAgentSource,
  KernelAgentSpawnRequest,
  KernelAgentSpawnResult,
  KernelCapabilityFamily,
  KernelCapabilityFilter,
  KernelCapabilityGroups,
  KernelCapabilityView,
  KernelCommandDescriptor,
  KernelCommandEntry,
  KernelCommandExecuteRequest,
  KernelCommandExecutionResult,
  KernelCommandFilter,
  KernelCommandResult,
  KernelConversation,
  KernelConversationOptions,
  KernelCoordinatorTaskStatus,
  KernelHookDescriptor,
  KernelHookFilter,
  KernelHookMutationResult,
  KernelHookRegisterRequest,
  KernelHookRunRequest,
  KernelHookRunResult,
  KernelHookSource,
  KernelHookType,
  KernelMcpAuthAction,
  KernelMcpAuthRequest,
  KernelMcpConnectRequest,
  KernelMcpConnectionState,
  KernelMcpLifecycleResult,
  KernelMcpResourceRef,
  KernelMcpServerRef,
  KernelMcpSetEnabledRequest,
  KernelMcpSnapshot,
  KernelMcpToolBinding,
  KernelMcpTransport,
  KernelPluginComponents,
  KernelPluginDescriptor,
  KernelPluginErrorDescriptor,
  KernelPluginFilter,
  KernelPluginInstallRequest,
  KernelPluginMutationResult,
  KernelPluginSnapshot,
  KernelPluginScope,
  KernelPluginSetEnabledRequest,
  KernelPluginStatus,
  KernelPluginUninstallRequest,
  KernelPluginUpdateRequest,
  KernelRunTurnAndWaitOptions,
  KernelRunTurnOptions,
  KernelRuntime,
  KernelRuntimeAgents,
  KernelRuntimeCapabilities,
  KernelRuntimeCommandDescriptor,
  KernelRuntimeCommandKind,
  KernelRuntimeContextManager,
  KernelRuntimeCommands,
  KernelRuntimeEventCategory,
  KernelRuntimeEventReplayOptions,
  KernelRuntimeEventScope,
  KernelRuntimeEventTaxonomyEntry,
  KernelRuntimeEventType,
  KernelRuntimeOptions,
  KernelRuntimePermissions,
  KernelRuntimeSessionManager,
  KernelRuntimeSessionResumeOptions,
  KernelRuntimeHooks,
  KernelRuntimeMcp,
  KernelRuntimePlugins,
  KernelRuntimeSkills,
  KernelRuntimeTasks,
  KernelRuntimeTools,
  KernelRuntimeToolSafety,
  KernelRuntimeToolSource,
  KernelRuntimeTransportConfig,
  KernelSkillContext,
  KernelSkillDescriptor,
  KernelSkillFilter,
  KernelSkillPromptContextRequest,
  KernelSkillPromptContextResult,
  KernelSkillSource,
  KernelTaskAssignRequest,
  KernelTaskCreateRequest,
  KernelTaskDescriptor,
  KernelTaskExecutionMetadata,
  KernelTaskFilter,
  KernelTaskListOptions,
  KernelTaskMutationResult,
  KernelTaskSnapshot,
  KernelTaskUpdateRequest,
  KernelRuntimeEventEnvelope,
  KernelRuntimeEventHandler,
  KernelToolDescriptor,
  KernelToolCallRequest,
  KernelToolCallResult,
  KernelToolFilter,
  KernelTurn,
  KernelTurnCompletedEvent,
  KernelTurnEventType,
  KernelTurnEventReplayOptions,
  KernelTurnFailedEvent,
  KernelTurnOutputDeltaEvent,
  KernelWaitForTurnOptions,
  KnownKernelRuntimeEventEnvelope,
} from './runtime.js'
export {
  createKernelRuntimeEventFacade,
  consumeKernelRuntimeEventMessage,
  getKernelEventFromEnvelope,
  getKernelRuntimeEnvelopeFromMessage,
  isKernelRuntimeEnvelope,
  KernelRuntimeEventReplayError,
  toKernelRuntimeEventMessage,
} from './events.js'
export type {
  KernelRuntimeEventMessage,
  KernelRuntimeEventFacade,
  KernelRuntimeEventFacadeOptions,
  KernelRuntimeEventInput,
  KernelRuntimeEventReplayRequest,
} from './events.js'
export {
  createKernelPermissionBroker,
  KernelPermissionBrokerDisposedError,
  KernelPermissionDecisionError,
} from './permissions.js'
export type {
  KernelPermissionBroker,
  KernelPermissionBrokerOptions,
  KernelPermissionBrokerSnapshot,
  KernelPermissionDecisionHandler,
  KernelPermissionSessionGrantKeyFactory,
} from './permissions.js'
export {
  createDefaultKernelRuntimeWireRouter,
  createKernelRuntimeInProcessWireTransport,
  createKernelRuntimeStdioWireTransport,
  createKernelRuntimeWireClient,
  KERNEL_RUNTIME_COMMAND_SCHEMA_VERSION,
  runKernelRuntimeWireProtocol,
} from './wireProtocol.js'
export type {
  KernelCapabilityDescriptor,
  KernelCapabilityReloadScope,
  KernelEvent,
  KernelPermissionDecision,
  KernelPermissionDecisionSource,
  KernelPermissionDecisionValue,
  KernelPermissionRequest,
  KernelPermissionRequestId,
  KernelPermissionRisk,
  KernelRuntimeAssignTaskCommand,
  KernelRuntimeAuthenticateMcpCommand,
  KernelRuntimeAuthenticateMcpResult,
  KernelRuntimeCancelAgentRunCommand,
  KernelRuntimeCancelAgentRunResult,
  KernelRuntimeCallToolCommand,
  KernelRuntimeCallToolResult,
  KernelRuntimeCommand,
  KernelRuntimeCommandType,
  KernelRuntimeConnectHostCommand,
  KernelRuntimeConnectMcpCommand,
  KernelRuntimeConnectMcpResult,
  KernelRuntimeCreateTaskCommand,
  KernelRuntimeDecidePermissionCommand,
  KernelRuntimeDisconnectHostCommand,
  KernelRuntimeExecuteCommandCommand,
  KernelRuntimeExecuteCommandResult,
  KernelRuntimeGetAgentOutputCommand,
  KernelRuntimeGetAgentOutputResult,
  KernelRuntimeGetAgentRunCommand,
  KernelRuntimeGetAgentRunResult,
  KernelRuntimeGetTaskCommand,
  KernelRuntimeAgentProcessExecutorOptions,
  KernelRuntimeHeadlessProcessExecutorOptions,
  KernelRuntimeHostDisconnectPolicy,
  KernelRuntimeHostIdentity,
  KernelRuntimeHostKind,
  KernelRuntimeInstallPluginCommand,
  KernelRuntimeInstallPluginResult,
  KernelRuntimeListAgentRunsCommand,
  KernelRuntimeListAgentRunsResult,
  KernelRuntimeListAgentsCommand,
  KernelRuntimeListAgentsResult,
  KernelRuntimeListHooksCommand,
  KernelRuntimeListHooksResult,
  KernelRuntimeListMcpResourcesCommand,
  KernelRuntimeListMcpResourcesResult,
  KernelRuntimeListMcpServersCommand,
  KernelRuntimeListMcpServersResult,
  KernelRuntimeListMcpToolsCommand,
  KernelRuntimeListMcpToolsResult,
  KernelRuntimeListPluginsCommand,
  KernelRuntimeListPluginsResult,
  KernelRuntimeListSkillsCommand,
  KernelRuntimeListSkillsResult,
  KernelRuntimeListTasksCommand,
  KernelRuntimeListTasksResult,
  KernelRuntimeListToolsCommand,
  KernelRuntimeListToolsResult,
  KernelRuntimeReloadAgentsCommand,
  KernelRuntimeReloadAgentsResult,
  KernelRuntimeReloadHooksCommand,
  KernelRuntimeReloadHooksResult,
  KernelRuntimeReloadMcpCommand,
  KernelRuntimeReloadMcpResult,
  KernelRuntimeReloadPluginsCommand,
  KernelRuntimeReloadPluginsResult,
  KernelRuntimeReloadSkillsCommand,
  KernelRuntimeReloadSkillsResult,
  KernelRuntimeRegisterHookCommand,
  KernelRuntimeRegisterHookResult,
  KernelRuntimeResolveSkillContextCommand,
  KernelRuntimeResolveSkillContextResult,
  KernelRuntimeRunHookCommand,
  KernelRuntimeRunHookResult,
  KernelRuntimeSetMcpEnabledCommand,
  KernelRuntimeSetMcpEnabledResult,
  KernelRuntimeSetPluginEnabledCommand,
  KernelRuntimeSetPluginEnabledResult,
  KernelRuntimeSpawnAgentCommand,
  KernelRuntimeSpawnAgentResult,
  KernelRuntimeTaskMutationResult,
  KernelRuntimeTransportKind,
  KernelRuntimeTrustLevel,
  KernelRuntimeUninstallPluginCommand,
  KernelRuntimeUninstallPluginResult,
  KernelRuntimeUpdatePluginCommand,
  KernelRuntimeUpdatePluginResult,
  KernelRuntimeUpdateTaskCommand,
  KernelRuntimeInProcessWireTransportOptions,
  KernelRuntimeStdioWireTransportOptions,
  KernelRuntimeWireClient,
  KernelRuntimeWireClientCommand,
  KernelRuntimeWireClientOptions,
  KernelRuntimeWireAgentRegistry,
  KernelRuntimeWireCapabilityResolver,
  KernelRuntimeWireConversationRecoverySnapshot,
  KernelRuntimeWireConversationSnapshotStore,
  KernelRuntimeWirePermissionBroker,
  KernelRuntimeWireProtocolOptions,
  KernelRuntimeWireRouter,
  KernelRuntimeWireRunnerOptions,
  KernelRuntimeWireTaskRegistry,
  KernelRuntimeWireTransport,
  KernelRuntimeWireTurnExecutionContext,
  KernelRuntimeWireTurnExecutionEvent,
  KernelRuntimeWireTurnExecutionResult,
  KernelRuntimeWireTurnExecutor,
} from './wireProtocol.js'
